### ISSUE TITLE
bouton participer à projet

### ISSUE THREAD

**Issue by bloic** [WildCodeSchool/orleans-php-202009-project-ideoz#228]
redirige sur une page erreur 500

**Comment by AmelieRoussel** [comment]
t'étais pas connecté en tant qu'admin ?

**Comment by bloic** [comment]
non

**Comment by AmelieRoussel** [comment]
et t'as bien rempli le mailer DSN ?

**Comment by bloic** [comment]
oui j'ai mis celui mailtrap

**Comment by AmelieRoussel** [comment]
dac merci, je vais chercher d'où vient le problème alors
