### ISSUE TITLE
w3c validator page home 

### ISSUE THREAD

**Issue by MaevaPllt** [WildCodeSchool/orleans-php-202009-project-ideoz#234]
Il y a des erreurs sur la page home ( à revérifier parce que ça a l'air d'être en rapport avec twig...)

**Comment by Flichyn** [comment]
Tu as copié le fichier directement ou tu as copié/collé le code source de la page depuis ton navigateur ?

**Comment by MaevaPllt** [comment]
j'ai copié-collé depuis l'IDE, ça fait peut-être une différence ?

**Comment by MaevaPllt** [comment]
Cette fois j'ai copié-collé depuis le code source, ça affiche toujours des erreurs mais là forcément plus associées à twig ^^

**Comment by Flichyn** [comment]
Voilà, le truc c'est justement de copier-coller depuis le code source, sinon évidemment avec Twig il aime pas trop :p Ça marche, on regarde ça !

**Comment by Gambino-stack** [comment]
ok
