### ISSUE TITLE
Admin / Espace partenaires

### ISSUE THREAD

**Issue by kevinvanphavong** [WildCodeSchool/orleans-php-202009-project-ideoz#240]
Le site est vraiment propre mais soyons tatillons : 
Le filtre de recherche ne fait pas la distinction entre SAS et S.A.S.
Si vous avez beaucoup d'entreprises et que vous avez oublié le nom d'une mais pas son format d'entreprise, le mot clé SAS ne renverra par les entreprises inscrites avec S.A.S écrit comme ça.

(je ne le labellise par en "fix", à vous de voir si c'est pertinent de corriger ça)

**Comment by AmelieRoussel** [comment]
pas bête, le soucis c'est qu'il faudrait passer par la prononciation je pense (comme dans le livecoding de Sylvain) donc je pense pas qu'on le fera XD
