### ISSUE TITLE
Page admin / ecosystème 

### ISSUE THREAD

**Issue by kevinvanphavong** [WildCodeSchool/orleans-php-202009-project-ideoz#242]
Pensez vous pas qu'il vaut mieux trier par 'id' => 'DESC' l'affichage des ecosystèmes ? 
Car dès lorsqu'on en créé un nouveau, on doit le rechercher en défilant la liste ou utiliser les filtres alors qu'il pourrait être le premier de la liste.

(Pas nécessairement un fix selon vos critères)

**Comment by Flichyn** [comment]
C'est encore en discussion au siège B)
