### ISSUE TITLE
Données à renseigner côté utilisateur

### ISSUE THREAD

**Issue by calouvts** [WildCodeSchool/orleans-php-202009-project-ideoz#243]
Votre utilisateur s'inscrit
Une fois inscrit il a un formulaire ou il renseigne ses informations : le numéro de téléphone n'est pas obligatoire, par contre il l'est sur la validation/acceptation de de l'utilisateur, 

Je mettrais l'obligation côté client et pas seulement côté admin

**Comment by AmelieRoussel** [comment]
c'est une erreur coté admin, il ne devrait pas être obligatoire du tout (j'ai vu le bug ce matin XD)
